Traceback (most recent call last):
  File "/github/home/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/github/home/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/github/home/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/github/home/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/github/home/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/github/home/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/github/home/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from viam import logging
from viam.robot.client import RobotClient
from viam.rpc.dial import DialOptions, dial_direct

async with await dial_direct('localhost:9090', DialOptions(insecure=True)) as channel:
    robot = await RobotClient.with_channel(channel, RobotClient.Options(refresh_interval=10, log_level=logging.FATAL))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mviam[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrpc[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdial[39;00m [38;5;28;01mimport[39;00m DialOptions, dial_direct
[1;32m      5[0m [38;5;28;01masync[39;00m [38;5;28;01mwith[39;00m [38;5;28;01mawait[39;00m dial_direct([38;5;124m'[39m[38;5;124mlocalhost:9090[39m[38;5;124m'[39m, DialOptions(insecure[38;5;241m=[39m[38;5;28;01mTrue[39;00m)) [38;5;28;01mas[39;00m channel:
[0;32m----> 6[0m     robot [38;5;241m=[39m [38;5;28;01mawait[39;00m RobotClient[38;5;241m.[39mwith_channel(channel, RobotClient[38;5;241m.[39mOptions(refresh_interval[38;5;241m=[39m[38;5;241m10[39m, log_level[38;5;241m=[39mlogging[38;5;241m.[39mFATAL))

File [0;32m/__w/python-sdk/python-sdk/src/viam/robot/client.py:106[0m, in [0;36mRobotClient.with_channel[0;34m(cls, channel, options)[0m
[1;32m    104[0m [38;5;28mself[39m[38;5;241m.[39m_resource_names [38;5;241m=[39m []
[1;32m    105[0m [38;5;28mself[39m[38;5;241m.[39m_should_close_channel [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m--> 106[0m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39mrefresh()
[1;32m    108[0m [38;5;28;01mif[39;00m options[38;5;241m.[39mrefresh_interval [38;5;241m>[39m [38;5;241m0[39m:
[1;32m    109[0m     [38;5;28mself[39m[38;5;241m.[39m_refresh_task [38;5;241m=[39m asyncio[38;5;241m.[39mcreate_task([38;5;28mself[39m[38;5;241m.[39m_refresh_every(options[38;5;241m.[39mrefresh_interval),
[1;32m    110[0m                                              name[38;5;241m=[39m[38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mviam[38;5;241m.[39m_TASK_PREFIX[38;5;132;01m}[39;00m[38;5;124m-robot_refresh_metadata[39m[38;5;124m'[39m)

File [0;32m/__w/python-sdk/python-sdk/src/viam/robot/client.py:126[0m, in [0;36mRobotClient.refresh[0;34m(self)[0m
[1;32m    122[0m [38;5;28;01masync[39;00m [38;5;28;01mdef[39;00m [38;5;21mrefresh[39m([38;5;28mself[39m):
[1;32m    123[0m     [38;5;124;03m"""[39;00m
[1;32m    124[0m [38;5;124;03m    Manually refresh the underlying parts of this robot[39;00m
[1;32m    125[0m [38;5;124;03m    """[39;00m
[0;32m--> 126[0m     response: ResourceNamesResponse [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_client[38;5;241m.[39mResourceNames(ResourceNamesRequest())
[1;32m    127[0m     resource_names: List[ResourceName] [38;5;241m=[39m [38;5;28mlist[39m(response[38;5;241m.[39mresources)
[1;32m    128[0m     [38;5;28;01mif[39;00m resource_names [38;5;241m==[39m [38;5;28mself[39m[38;5;241m.[39m_resource_names:

File [0;32m~/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/grpclib/client.py:882[0m, in [0;36mUnaryUnaryMethod.__call__[0;34m(self, message, timeout, metadata)[0m
[1;32m    874[0m [38;5;124;03m"""Coroutine to perform defined call.[39;00m
[1;32m    875[0m 
[1;32m    876[0m [38;5;124;03m:param message: message[39;00m
[0;32m   (...)[0m
[1;32m    879[0m [38;5;124;03m:return: message[39;00m
[1;32m    880[0m [38;5;124;03m"""[39;00m
[1;32m    881[0m [38;5;28;01masync[39;00m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mopen(timeout[38;5;241m=[39mtimeout, metadata[38;5;241m=[39mmetadata) [38;5;28;01mas[39;00m stream:
[0;32m--> 882[0m     [38;5;28;01mawait[39;00m stream[38;5;241m.[39msend_message(message, end[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    883[0m     reply [38;5;241m=[39m [38;5;28;01mawait[39;00m stream[38;5;241m.[39mrecv_message()
[1;32m    884[0m [38;5;28;01massert[39;00m reply [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m

File [0;32m~/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/grpclib/client.py:241[0m, in [0;36mStream.send_message[0;34m(self, message, end)[0m
[1;32m    221[0m [38;5;124;03m"""Coroutine to send message to the server.[39;00m
[1;32m    222[0m 
[1;32m    223[0m [38;5;124;03mIf client sends UNARY request, then you should call this coroutine only[39;00m
[0;32m   (...)[0m
[1;32m    238[0m [38;5;124;03madditional HTTP/2 frame.[39;00m
[1;32m    239[0m [38;5;124;03m"""[39;00m
[1;32m    240[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_send_request_done:
[0;32m--> 241[0m     [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39msend_request()
[1;32m    243[0m end_stream [38;5;241m=[39m end
[1;32m    244[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_cardinality[38;5;241m.[39mclient_streaming:

File [0;32m~/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/grpclib/client.py:173[0m, in [0;36mStream.send_request[0;34m(self, end)[0m
[1;32m    169[0m     [38;5;28;01mraise[39;00m ProtocolError([38;5;124m'[39m[38;5;124mUnary request requires a message to be sent [39m[38;5;124m'[39m
[1;32m    170[0m                         [38;5;124m'[39m[38;5;124mbefore ending outgoing stream[39m[38;5;124m'[39m)
[1;32m    172[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39m_wrapper:
[0;32m--> 173[0m     protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m__connect__()
[1;32m    174[0m     stream [38;5;241m=[39m protocol[38;5;241m.[39mprocessor[38;5;241m.[39mconnection\
[1;32m    175[0m         [38;5;241m.[39mcreate_stream(wrapper[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_wrapper)
[1;32m    177[0m     headers [38;5;241m=[39m [
[1;32m    178[0m         ([38;5;124m'[39m[38;5;124m:method[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mPOST[39m[38;5;124m'[39m),
[1;32m    179[0m         ([38;5;124m'[39m[38;5;124m:scheme[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m_scheme),
[1;32m    180[0m         ([38;5;124m'[39m[38;5;124m:path[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_method_name),
[1;32m    181[0m         ([38;5;124m'[39m[38;5;124m:authority[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m_authority),
[1;32m    182[0m     ]

File [0;32m~/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/grpclib/client.py:728[0m, in [0;36mChannel.__connect__[0;34m(self)[0m
[1;32m    726[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_connected:
[1;32m    727[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 728[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_create_connection()
[1;32m    729[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[1;32m    730[0m         [38;5;28mself[39m[38;5;241m.[39m_state [38;5;241m=[39m _ChannelState[38;5;241m.[39mTRANSIENT_FAILURE

File [0;32m~/.cache/pypoetry/virtualenvs/viam-vvGuc1L8-py3.9/lib/python3.9/site-packages/grpclib/client.py:711[0m, in [0;36mChannel._create_connection[0;34m(self)[0m
[1;32m    707[0m     _, protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_loop[38;5;241m.[39mcreate_unix_connection(
[1;32m    708[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol_factory, [38;5;28mself[39m[38;5;241m.[39m_path, ssl[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_ssl,
[1;32m    709[0m     )
[1;32m    710[0m [38;5;28;01melse[39;00m:
[0;32m--> 711[0m     _, protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_loop[38;5;241m.[39mcreate_connection(
[1;32m    712[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol_factory, [38;5;28mself[39m[38;5;241m.[39m_host, [38;5;28mself[39m[38;5;241m.[39m_port,
[1;32m    713[0m         ssl[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_ssl,
[1;32m    714[0m     )
[1;32m    715[0m [38;5;28;01mreturn[39;00m cast(H2Protocol, protocol)

File [0;32m/usr/lib/python3.9/asyncio/base_events.py:1064[0m, in [0;36mBaseEventLoop.create_connection[0;34m(self, protocol_factory, host, port, ssl, family, proto, flags, sock, local_addr, server_hostname, ssl_handshake_timeout, happy_eyeballs_delay, interleave)[0m
[1;32m   1061[0m                 [38;5;28;01mraise[39;00m exceptions[[38;5;241m0[39m]
[1;32m   1062[0m             [38;5;66;03m# Raise a combined exception so the user can see all[39;00m
[1;32m   1063[0m             [38;5;66;03m# the various error messages.[39;00m
[0;32m-> 1064[0m             [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m([38;5;124m'[39m[38;5;124mMultiple exceptions: [39m[38;5;132;01m{}[39;00m[38;5;124m'[39m[38;5;241m.[39mformat(
[1;32m   1065[0m                 [38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([38;5;28mstr[39m(exc) [38;5;28;01mfor[39;00m exc [38;5;129;01min[39;00m exceptions)))
[1;32m   1067[0m [38;5;28;01melse[39;00m:
[1;32m   1068[0m     [38;5;28;01mif[39;00m sock [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

[0;31mOSError[0m: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 9090), [Errno 99] Cannot assign requested address
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 9090), [Errno 99] Cannot assign requested address

