Traceback (most recent call last):
  File "/github/home/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/github/home/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/github/home/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/github/home/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/github/home/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/github/home/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/github/home/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from viam import logging
from viam.robot.client import RobotClient
from viam.rpc.dial import DialOptions

async def connect() -> RobotClient:
    options = RobotClient.Options(
        dial_options=DialOptions(insecure=True),
        log_level=logging.FATAL
    )
    return await RobotClient.at_address('0.0.0.0:9090', options)

robot = await connect()
print(robot.resource_names)
await robot.close()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mConnectionRefusedError[0m                    Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 12>[0;34m()[0m
[1;32m      6[0m     options [38;5;241m=[39m RobotClient[38;5;241m.[39mOptions(
[1;32m      7[0m         dial_options[38;5;241m=[39mDialOptions(insecure[38;5;241m=[39m[38;5;28;01mTrue[39;00m),
[1;32m      8[0m         log_level[38;5;241m=[39mlogging[38;5;241m.[39mFATAL
[1;32m      9[0m     )
[1;32m     10[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m RobotClient[38;5;241m.[39mat_address([38;5;124m'[39m[38;5;124m0.0.0.0:9090[39m[38;5;124m'[39m, options)
[0;32m---> 12[0m robot [38;5;241m=[39m [38;5;28;01mawait[39;00m connect()
[1;32m     13[0m [38;5;28mprint[39m(robot[38;5;241m.[39mresource_names)
[1;32m     14[0m [38;5;28;01mawait[39;00m robot[38;5;241m.[39mclose()

Input [0;32mIn [2][0m, in [0;36mconnect[0;34m()[0m
[1;32m      5[0m [38;5;28;01masync[39;00m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m() [38;5;241m-[39m[38;5;241m>[39m RobotClient:
[1;32m      6[0m     options [38;5;241m=[39m RobotClient[38;5;241m.[39mOptions(
[1;32m      7[0m         dial_options[38;5;241m=[39mDialOptions(insecure[38;5;241m=[39m[38;5;28;01mTrue[39;00m),
[1;32m      8[0m         log_level[38;5;241m=[39mlogging[38;5;241m.[39mFATAL
[1;32m      9[0m     )
[0;32m---> 10[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m RobotClient[38;5;241m.[39mat_address([38;5;124m'[39m[38;5;124m0.0.0.0:9090[39m[38;5;124m'[39m, options)

File [0;32m/__w/viam-python-sdk/viam-python-sdk/src/viam/robot/client.py:90[0m, in [0;36mRobotClient.at_address[0;34m(cls, address, options)[0m
[1;32m     80[0m [38;5;124;03m"""Create a robot client that is connected to the robot at the provided address.[39;00m
[1;32m     81[0m 
[1;32m     82[0m [38;5;124;03mArgs:[39;00m
[0;32m   (...)[0m
[1;32m     87[0m [38;5;124;03m    Self: the RobotClient[39;00m
[1;32m     88[0m [38;5;124;03m"""[39;00m
[1;32m     89[0m channel [38;5;241m=[39m [38;5;28;01mawait[39;00m dial_direct(address, options[38;5;241m.[39mdial_options)
[0;32m---> 90[0m robot [38;5;241m=[39m [38;5;28;01mawait[39;00m RobotClient[38;5;241m.[39mwith_channel(channel, options)
[1;32m     91[0m robot[38;5;241m.[39m_should_close_channel [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m     92[0m [38;5;28;01mreturn[39;00m robot

File [0;32m/__w/viam-python-sdk/viam-python-sdk/src/viam/robot/client.py:116[0m, in [0;36mRobotClient.with_channel[0;34m(cls, channel, options)[0m
[1;32m    114[0m [38;5;28mself[39m[38;5;241m.[39m_resource_names [38;5;241m=[39m []
[1;32m    115[0m [38;5;28mself[39m[38;5;241m.[39m_should_close_channel [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m--> 116[0m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39mrefresh()
[1;32m    118[0m [38;5;28;01mif[39;00m options[38;5;241m.[39mrefresh_interval [38;5;241m>[39m [38;5;241m0[39m:
[1;32m    119[0m     [38;5;28mself[39m[38;5;241m.[39m_refresh_task [38;5;241m=[39m asyncio[38;5;241m.[39mcreate_task(
[1;32m    120[0m         [38;5;28mself[39m[38;5;241m.[39m_refresh_every(options[38;5;241m.[39mrefresh_interval), name[38;5;241m=[39m[38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mviam[38;5;241m.[39m_TASK_PREFIX[38;5;132;01m}[39;00m[38;5;124m-robot_refresh_metadata[39m[38;5;124m"[39m
[1;32m    121[0m     )

File [0;32m/__w/viam-python-sdk/viam-python-sdk/src/viam/robot/client.py:137[0m, in [0;36mRobotClient.refresh[0;34m(self)[0m
[1;32m    133[0m [38;5;28;01masync[39;00m [38;5;28;01mdef[39;00m [38;5;21mrefresh[39m([38;5;28mself[39m):
[1;32m    134[0m     [38;5;124;03m"""[39;00m
[1;32m    135[0m [38;5;124;03m    Manually refresh the underlying parts of this robot[39;00m
[1;32m    136[0m [38;5;124;03m    """[39;00m
[0;32m--> 137[0m     response: ResourceNamesResponse [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_client[38;5;241m.[39mResourceNames(ResourceNamesRequest())
[1;32m    138[0m     resource_names: List[ResourceName] [38;5;241m=[39m [38;5;28mlist[39m(response[38;5;241m.[39mresources)
[1;32m    139[0m     [38;5;28;01mif[39;00m resource_names [38;5;241m==[39m [38;5;28mself[39m[38;5;241m.[39m_resource_names:

File [0;32m~/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/grpclib/client.py:881[0m, in [0;36mUnaryUnaryMethod.__call__[0;34m(self, message, timeout, metadata)[0m
[1;32m    873[0m [38;5;124;03m"""Coroutine to perform defined call.[39;00m
[1;32m    874[0m 
[1;32m    875[0m [38;5;124;03m:param message: message[39;00m
[0;32m   (...)[0m
[1;32m    878[0m [38;5;124;03m:return: message[39;00m
[1;32m    879[0m [38;5;124;03m"""[39;00m
[1;32m    880[0m [38;5;28;01masync[39;00m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mopen(timeout[38;5;241m=[39mtimeout, metadata[38;5;241m=[39mmetadata) [38;5;28;01mas[39;00m stream:
[0;32m--> 881[0m     [38;5;28;01mawait[39;00m stream[38;5;241m.[39msend_message(message, end[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    882[0m     reply [38;5;241m=[39m [38;5;28;01mawait[39;00m stream[38;5;241m.[39mrecv_message()
[1;32m    883[0m [38;5;28;01massert[39;00m reply [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m

File [0;32m~/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/grpclib/client.py:241[0m, in [0;36mStream.send_message[0;34m(self, message, end)[0m
[1;32m    221[0m [38;5;124;03m"""Coroutine to send message to the server.[39;00m
[1;32m    222[0m 
[1;32m    223[0m [38;5;124;03mIf client sends UNARY request, then you should call this coroutine only[39;00m
[0;32m   (...)[0m
[1;32m    238[0m [38;5;124;03madditional HTTP/2 frame.[39;00m
[1;32m    239[0m [38;5;124;03m"""[39;00m
[1;32m    240[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_send_request_done:
[0;32m--> 241[0m     [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39msend_request()
[1;32m    243[0m end_stream [38;5;241m=[39m end
[1;32m    244[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_cardinality[38;5;241m.[39mclient_streaming:

File [0;32m~/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/grpclib/client.py:173[0m, in [0;36mStream.send_request[0;34m(self, end)[0m
[1;32m    169[0m     [38;5;28;01mraise[39;00m ProtocolError([38;5;124m'[39m[38;5;124mUnary request requires a message to be sent [39m[38;5;124m'[39m
[1;32m    170[0m                         [38;5;124m'[39m[38;5;124mbefore ending outgoing stream[39m[38;5;124m'[39m)
[1;32m    172[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39m_wrapper:
[0;32m--> 173[0m     protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m__connect__()
[1;32m    174[0m     stream [38;5;241m=[39m protocol[38;5;241m.[39mprocessor[38;5;241m.[39mconnection\
[1;32m    175[0m         [38;5;241m.[39mcreate_stream(wrapper[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_wrapper)
[1;32m    177[0m     headers [38;5;241m=[39m [
[1;32m    178[0m         ([38;5;124m'[39m[38;5;124m:method[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mPOST[39m[38;5;124m'[39m),
[1;32m    179[0m         ([38;5;124m'[39m[38;5;124m:scheme[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m_scheme),
[1;32m    180[0m         ([38;5;124m'[39m[38;5;124m:path[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_method_name),
[1;32m    181[0m         ([38;5;124m'[39m[38;5;124m:authority[39m[38;5;124m'[39m, [38;5;28mself[39m[38;5;241m.[39m_channel[38;5;241m.[39m_authority),
[1;32m    182[0m     ]

File [0;32m~/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/grpclib/client.py:728[0m, in [0;36mChannel.__connect__[0;34m(self)[0m
[1;32m    726[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_connected:
[1;32m    727[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 728[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_create_connection()
[1;32m    729[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[1;32m    730[0m         [38;5;28mself[39m[38;5;241m.[39m_state [38;5;241m=[39m _ChannelState[38;5;241m.[39mTRANSIENT_FAILURE

File [0;32m~/.cache/pypoetry/virtualenvs/viam-BVXXZUuz-py3.9/lib/python3.9/site-packages/grpclib/client.py:711[0m, in [0;36mChannel._create_connection[0;34m(self)[0m
[1;32m    707[0m     _, protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_loop[38;5;241m.[39mcreate_unix_connection(
[1;32m    708[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol_factory, [38;5;28mself[39m[38;5;241m.[39m_path, ssl[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_ssl,
[1;32m    709[0m     )
[1;32m    710[0m [38;5;28;01melse[39;00m:
[0;32m--> 711[0m     _, protocol [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_loop[38;5;241m.[39mcreate_connection(
[1;32m    712[0m         [38;5;28mself[39m[38;5;241m.[39m_protocol_factory, [38;5;28mself[39m[38;5;241m.[39m_host, [38;5;28mself[39m[38;5;241m.[39m_port,
[1;32m    713[0m         ssl[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_ssl,
[1;32m    714[0m     )
[1;32m    715[0m [38;5;28;01mreturn[39;00m protocol

File [0;32m/usr/lib/python3.9/asyncio/base_events.py:1056[0m, in [0;36mBaseEventLoop.create_connection[0;34m(self, protocol_factory, host, port, ssl, family, proto, flags, sock, local_addr, server_hostname, ssl_handshake_timeout, happy_eyeballs_delay, interleave)[0m
[1;32m   1054[0m exceptions [38;5;241m=[39m [exc [38;5;28;01mfor[39;00m sub [38;5;129;01min[39;00m exceptions [38;5;28;01mfor[39;00m exc [38;5;129;01min[39;00m sub]
[1;32m   1055[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(exceptions) [38;5;241m==[39m [38;5;241m1[39m:
[0;32m-> 1056[0m     [38;5;28;01mraise[39;00m exceptions[[38;5;241m0[39m]
[1;32m   1057[0m [38;5;28;01melse[39;00m:
[1;32m   1058[0m     [38;5;66;03m# If they all have the same str(), raise one.[39;00m
[1;32m   1059[0m     model [38;5;241m=[39m [38;5;28mstr[39m(exceptions[[38;5;241m0[39m])

File [0;32m/usr/lib/python3.9/asyncio/base_events.py:1041[0m, in [0;36mBaseEventLoop.create_connection[0;34m(self, protocol_factory, host, port, ssl, family, proto, flags, sock, local_addr, server_hostname, ssl_handshake_timeout, happy_eyeballs_delay, interleave)[0m
[1;32m   1039[0m [38;5;28;01mfor[39;00m addrinfo [38;5;129;01min[39;00m infos:
[1;32m   1040[0m     [38;5;28;01mtry[39;00m:
[0;32m-> 1041[0m         sock [38;5;241m=[39m [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39m_connect_sock(
[1;32m   1042[0m             exceptions, addrinfo, laddr_infos)
[1;32m   1043[0m         [38;5;28;01mbreak[39;00m
[1;32m   1044[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:

File [0;32m/usr/lib/python3.9/asyncio/base_events.py:955[0m, in [0;36mBaseEventLoop._connect_sock[0;34m(self, exceptions, addr_info, local_addr_infos)[0m
[1;32m    953[0m         [38;5;28;01melse[39;00m:  [38;5;66;03m# all bind attempts failed[39;00m
[1;32m    954[0m             [38;5;28;01mraise[39;00m my_exceptions[38;5;241m.[39mpop()
[0;32m--> 955[0m     [38;5;28;01mawait[39;00m [38;5;28mself[39m[38;5;241m.[39msock_connect(sock, address)
[1;32m    956[0m     [38;5;28;01mreturn[39;00m sock
[1;32m    957[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m exc:

File [0;32m/usr/lib/python3.9/asyncio/selector_events.py:502[0m, in [0;36mBaseSelectorEventLoop.sock_connect[0;34m(self, sock, address)[0m
[1;32m    500[0m fut [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcreate_future()
[1;32m    501[0m [38;5;28mself[39m[38;5;241m.[39m_sock_connect(fut, sock, address)
[0;32m--> 502[0m [38;5;28;01mreturn[39;00m [38;5;28;01mawait[39;00m fut

File [0;32m/usr/lib/python3.9/asyncio/selector_events.py:537[0m, in [0;36mBaseSelectorEventLoop._sock_connect_cb[0;34m(self, fut, sock, address)[0m
[1;32m    534[0m     err [38;5;241m=[39m sock[38;5;241m.[39mgetsockopt(socket[38;5;241m.[39mSOL_SOCKET, socket[38;5;241m.[39mSO_ERROR)
[1;32m    535[0m     [38;5;28;01mif[39;00m err [38;5;241m!=[39m [38;5;241m0[39m:
[1;32m    536[0m         [38;5;66;03m# Jump to any except clause below.[39;00m
[0;32m--> 537[0m         [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m(err, [38;5;124mf[39m[38;5;124m'[39m[38;5;124mConnect call failed [39m[38;5;132;01m{[39;00maddress[38;5;132;01m}[39;00m[38;5;124m'[39m)
[1;32m    538[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mBlockingIOError[39;00m, [38;5;167;01mInterruptedError[39;00m):
[1;32m    539[0m     [38;5;66;03m# socket is still registered, the callback will be retried later[39;00m
[1;32m    540[0m     [38;5;28;01mpass[39;00m

[0;31mConnectionRefusedError[0m: [Errno 111] Connect call failed ('0.0.0.0', 9090)
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 9090)

